name = "Wynn Reloaded"
author = "jh-devv"
version = "fabric-v0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "376088bb260be786ddee968c0c66795b5892b804095206460801393a1b4a641c"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
