name = "Wynn Reloaded"
author = "jh-devv"
version = "fabric-v0.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82936f87ca26f5125854f79bafe7a0cd5b948ad6cd42e4c8283d3afffef13a06"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
