name = "Wynn Reloaded"
author = "jh-devv"
version = "fabric-v0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5135591bbe86564dc422224542de60417ade047bd3f65746154d74f978542c5"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
