name = "Wynn Reloaded"
author = "jh-devv"
version = "fabric-v0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3239aa1d3845b8c509722b58ccda905b54a3e33dad4ab128140050bba5b5e971"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
