name: 'Bump Modpack Action | Action'
description: 'Bump a modpacks version'

inputs:
  release-tag:
    description: 'The release tag to bump the modpack to'
    required: true
  modpack:
    description: 'Path to the modpack directory'
    required: false
    default: '.'
  pack-file:
    description: 'Path to the pack config file'
    required: false
    default: 'pack.toml'

runs:
  using: 'composite'
  
  steps:
    - name: Check Out Git Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Set the version
      run: sed -i 's/version = "[^"]*"/version = "${{ inputs.release-tag }}"/' ${{ inputs.modpack }}/${{ inputs.pack-file }}
      shell: bash
    
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -a -m "chore(${{ inputs.modpack }}): bump version to ${{ inputs.release-tag }}"
      shell: bash
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
